"""Criacao das tabelas iniciais

Revision ID: 36450ad06c16
Revises: 
Create Date: 2026-02-21 13:42:18.814977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36450ad06c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transportadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=False),
    sa.Column('numero_empenho', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_previsao_entrega', sa.DateTime(), nullable=True),
    sa.Column('valor_frete_estimado', sa.Float(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['nota_fiscal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_status')
    op.drop_table('nota_fiscal')
    op.drop_table('transportadora')
    op.drop_table('empresa')
    # ### end Alembic commands ###
