"""Adicionando cidade e estado destino

Revision ID: dfdca3d82a09
Revises: 44e91889898b
Create Date: 2026-02-23 12:51:19.328878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdca3d82a09'
down_revision = '44e91889898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_destino', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('estado_destino', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota_fiscal', schema=None) as batch_op:
        batch_op.drop_column('estado_destino')
        batch_op.drop_column('cidade_destino')

    # ### end Alembic commands ###
